export const weatherVariables = {
    hourly: [
        {
            id: "temperature_2m",
            label: "Temperature (2m)",
            unit: "°C",
            category: "Temperature",
            popular: true,
            description: "Air temperature at 2 meters above ground",
        },
        {
            id: "dew_point_2m",
            label: "Dew Point (2m)",
            unit: "°C",
            category: "Temperature",
            popular: false,
            description: "Dew point temperature at 2 meters above ground",
        },
        {
            id: "apparent_temperature",
            label: "Apparent Temperature",
            unit: "°C",
            category: "Temperature",
            popular: true,
            description: "Feels-like temperature combining wind chill, humidity and solar radiation",
        },
        {
            id: "relative_humidity_2m",
            label: "Relative Humidity (2m)",
            unit: "%",
            category: "Humidity",
            popular: true,
            description: "Relative humidity at 2 meters above ground",
        },
        {
            id: "vapour_pressure_deficit",
            label: "Vapor Pressure Deficit",
            unit: "kPa",
            category: "Humidity",
            popular: false,
            description: "VPD affects plant transpiration rates",
        },
        {
            id: "pressure_msl",
            label: "Sea Level Pressure",
            unit: "hPa",
            category: "Pressure",
            popular: false,
            description: "Atmospheric pressure reduced to mean sea level",
        },
        {
            id: "surface_pressure",
            label: "Surface Pressure",
            unit: "hPa",
            category: "Pressure",
            popular: false,
            description: "Atmospheric pressure at surface level",
        },
        {
            id: "precipitation",
            label: "Precipitation",
            unit: "mm",
            category: "Precipitation",
            popular: true,
            description: "Total precipitation (rain, showers, snow)",
        },
        {
            id: "rain",
            label: "Rain",
            unit: "mm",
            category: "Precipitation",
            popular: true,
            description: "Only liquid precipitation",
        },
        {
            id: "snowfall",
            label: "Snowfall",
            unit: "cm",
            category: "Precipitation",
            popular: false,
            description: "Snowfall amount in centimeters",
        },
        {
            id: "snow_depth",
            label: "Snow Depth",
            unit: "m",
            category: "Precipitation",
            popular: false,
            description: "Snow depth on the ground",
        },
        {
            id: "wind_speed_10m",
            label: "Wind Speed (10m)",
            unit: "km/h",
            category: "Wind",
            popular: true,
            description: "Wind speed at 10 meters above ground",
        },
        {
            id: "wind_speed_100m",
            label: "Wind Speed (100m)",
            unit: "km/h",
            category: "Wind",
            popular: false,
            description: "Wind speed at 100 meters above ground",
        },
        {
            id: "wind_direction_10m",
            label: "Wind Direction (10m)",
            unit: "°",
            category: "Wind",
            popular: false,
            description: "Wind direction at 10 meters above ground",
        },
        {
            id: "wind_direction_100m",
            label: "Wind Direction (100m)",
            unit: "°",
            category: "Wind",
            popular: false,
            description: "Wind direction at 100 meters above ground",
        },
        {
            id: "wind_gusts_10m",
            label: "Wind Gusts (10m)",
            unit: "km/h",
            category: "Wind",
            popular: false,
            description: "Maximum wind gusts at 10 meters",
        },
        {
            id: "cloud_cover",
            label: "Total Cloud Cover",
            unit: "%",
            category: "Clouds",
            popular: false,
            description: "Total cloud cover as area fraction",
        },
        {
            id: "cloud_cover_low",
            label: "Low Cloud Cover",
            unit: "%",
            category: "Clouds",
            popular: false,
            description: "Low level clouds up to 2km altitude",
        },
        {
            id: "cloud_cover_mid",
            label: "Mid Cloud Cover",
            unit: "%",
            category: "Clouds",
            popular: false,
            description: "Mid level clouds 2-6km altitude",
        },
        {
            id: "cloud_cover_high",
            label: "High Cloud Cover",
            unit: "%",
            category: "Clouds",
            popular: false,
            description: "High level clouds above 6km",
        },
        {
            id: "shortwave_radiation",
            label: "Solar Radiation",
            unit: "W/m²",
            category: "Solar",
            popular: false,
            description: "Shortwave solar radiation",
        },
        {
            id: "direct_radiation",
            label: "Direct Solar Radiation",
            unit: "W/m²",
            category: "Solar",
            popular: false,
            description: "Direct solar radiation on horizontal plane",
        },
        {
            id: "direct_normal_irradiance",
            label: "Direct Normal Irradiance",
            unit: "W/m²",
            category: "Solar",
            popular: false,
            description: "Direct solar radiation perpendicular to sun",
        },
        {
            id: "diffuse_radiation",
            label: "Diffuse Solar Radiation",
            unit: "W/m²",
            category: "Solar",
            popular: false,
            description: "Diffuse solar radiation",
        },
        {
            id: "sunshine_duration",
            label: "Sunshine Duration",
            unit: "s",
            category: "Solar",
            popular: false,
            description: "Seconds of sunshine per hour",
        },
        {
            id: "soil_temperature_0_to_7cm",
            label: "Soil Temperature (0-7cm)",
            unit: "°C",
            category: "Soil",
            popular: false,
            description: "Average soil temperature 0-7cm depth",
        },
        {
            id: "soil_temperature_7_to_28cm",
            label: "Soil Temperature (7-28cm)",
            unit: "°C",
            category: "Soil",
            popular: false,
            description: "Average soil temperature 7-28cm depth",
        },
        {
            id: "soil_temperature_28_to_100cm",
            label: "Soil Temperature (28-100cm)",
            unit: "°C",
            category: "Soil",
            popular: false,
            description: "Average soil temperature 28-100cm depth",
        },
        {
            id: "soil_temperature_100_to_255cm",
            label: "Soil Temperature (100-255cm)",
            unit: "°C",
            category: "Soil",
            popular: false,
            description: "Average soil temperature 100-255cm depth",
        },
        {
            id: "soil_moisture_0_to_7cm",
            label: "Soil Moisture (0-7cm)",
            unit: "m³/m³",
            category: "Soil",
            popular: false,
            description: "Soil water content 0-7cm depth",
        },
        {
            id: "soil_moisture_7_to_28cm",
            label: "Soil Moisture (7-28cm)",
            unit: "m³/m³",
            category: "Soil",
            popular: false,
            description: "Soil water content 7-28cm depth",
        },
        {
            id: "soil_moisture_28_to_100cm",
            label: "Soil Moisture (28-100cm)",
            unit: "m³/m³",
            category: "Soil",
            popular: false,
            description: "Soil water content 28-100cm depth",
        },
        {
            id: "soil_moisture_100_to_255cm",
            label: "Soil Moisture (100-255cm)",
            unit: "m³/m³",
            category: "Soil",
            popular: false,
            description: "Soil water content 100-255cm depth",
        },
        {
            id: "et0_fao_evapotranspiration",
            label: "Evapotranspiration (ET₀)",
            unit: "mm",
            category: "Agriculture",
            popular: false,
            description: "Reference evapotranspiration for irrigation",
        },
        {
            id: "weather_code",
            label: "Weather Code",
            unit: "WMO",
            category: "General",
            popular: false,
            description: "Weather condition as numeric code",
        },
    ],
    daily: [
        {
            id: "temperature_2m_max",
            label: "Max Temperature",
            unit: "°C",
            category: "Temperature",
            popular: true,
            description: "Maximum daily temperature",
        },
        {
            id: "temperature_2m_min",
            label: "Min Temperature",
            unit: "°C",
            category: "Temperature",
            popular: true,
            description: "Minimum daily temperature",
        },
        {
            id: "apparent_temperature_max",
            label: "Max Apparent Temperature",
            unit: "°C",
            category: "Temperature",
            popular: false,
            description: "Maximum daily apparent temperature",
        },
        {
            id: "apparent_temperature_min",
            label: "Min Apparent Temperature",
            unit: "°C",
            category: "Temperature",
            popular: false,
            description: "Minimum daily apparent temperature",
        },
        {
            id: "precipitation_sum",
            label: "Precipitation Sum",
            unit: "mm",
            category: "Precipitation",
            popular: true,
            description: "Total daily precipitation",
        },
        {
            id: "rain_sum",
            label: "Rain Sum",
            unit: "mm",
            category: "Precipitation",
            popular: true,
            description: "Total daily rain",
        },
        {
            id: "snowfall_sum",
            label: "Snowfall Sum",
            unit: "cm",
            category: "Precipitation",
            popular: false,
            description: "Total daily snowfall",
        },
        {
            id: "precipitation_hours",
            label: "Precipitation Hours",
            unit: "h",
            category: "Precipitation",
            popular: false,
            description: "Hours with precipitation",
        },
        {
            id: "wind_speed_10m_max",
            label: "Max Wind Speed",
            unit: "km/h",
            category: "Wind",
            popular: false,
            description: "Maximum daily wind speed",
        },
        {
            id: "wind_gusts_10m_max",
            label: "Max Wind Gusts",
            unit: "km/h",
            category: "Wind",
            popular: false,
            description: "Maximum daily wind gusts",
        },
        {
            id: "wind_direction_10m_dominant",
            label: "Dominant Wind Direction",
            unit: "°",
            category: "Wind",
            popular: false,
            description: "Most common wind direction",
        },
        {
            id: "sunrise",
            label: "Sunrise",
            unit: "ISO8601",
            category: "Solar",
            popular: false,
            description: "Sunrise time",
        },
        {
            id: "sunset",
            label: "Sunset",
            unit: "ISO8601",
            category: "Solar",
            popular: false,
            description: "Sunset time",
        },
        {
            id: "sunshine_duration",
            label: "Sunshine Duration",
            unit: "s",
            category: "Solar",
            popular: false,
            description: "Total daily sunshine duration",
        },
        {
            id: "daylight_duration",
            label: "Daylight Duration",
            unit: "s",
            category: "Solar",
            popular: false,
            description: "Total daylight duration",
        },
        {
            id: "shortwave_radiation_sum",
            label: "Solar Radiation Sum",
            unit: "MJ/m²",
            category: "Solar",
            popular: false,
            description: "Total daily solar radiation",
        },
        {
            id: "et0_fao_evapotranspiration",
            label: "Daily Evapotranspiration",
            unit: "mm",
            category: "Agriculture",
            popular: false,
            description: "Daily reference evapotranspiration",
        },
        {
            id: "weather_code",
            label: "Weather Code",
            unit: "WMO",
            category: "General",
            popular: false,
            description: "Most severe daily weather condition",
        },
    ],
}

export const weatherModels = [
    { id: "best_match", label: "Best Match (Auto)", description: "Automatically selects the best model for the location" },
    { id: "era5", label: "ERA5", description: "Global reanalysis with 25km resolution" },
    { id: "era5_land", label: "ERA5-Land", description: "Enhanced resolution global model (9km)" },
    { id: "cerra", label: "CERRA", description: "Regional model for Europe (5.5km)" },
]

export const units = {
    temperature: [
        { id: "celsius", label: "Celsius (°C)" },
        { id: "fahrenheit", label: "Fahrenheit (°F)" },
    ],
    wind_speed: [
        { id: "kmh", label: "km/h" },
        { id: "ms", label: "m/s" },
        { id: "mph", label: "mph" },
        { id: "kn", label: "kn" },
    ],
    precipitation: [
        { id: "mm", label: "mm" },
        { id: "inch", label: "inch" },
    ],
}
